Vagrant.configure("2") do |config|
  
  config.vm.define("server") do |sv|
  
    sv.vm.box = "generic/debian10"
    sv.vm.hostname = "schahid"
    sv.vm.network "private_network", ip: "192.168.56.110"
    sv.vm.provider("virtualbox") do |vb|
      vb.name = "server-gns"
      vb.memory = "2048"
      vb.cpus = 2
    end

    sv.vm.provision "shell", path: "scripts/init.sh"
  end

end
